//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmler.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class table1
    {
        public int userId { get; set; }
        public string usernName { get; set; }
        public string email { get; set; }
    }
}
