//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islem
    {
        public int Islem_ID { get; set; }
        public Nullable<int> Ogrenci_ID { get; set; }
        public Nullable<int> Kitap_ID { get; set; }
        public Nullable<System.DateTime> Aliş_Tar { get; set; }
        public Nullable<System.DateTime> Veriş_Tar { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
