//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public Kitap()
        {
            this.Islem = new HashSet<Islem>();
        }
    
        public int Kitap_ID { get; set; }
        public string Kitap_Adi { get; set; }
        public Nullable<int> Yazar_ID { get; set; }
        public Nullable<int> Tur_ID { get; set; }
        public Nullable<int> S_Sayisi { get; set; }
        public Nullable<int> Puan { get; set; }
    
        public virtual ICollection<Islem> Islem { get; set; }
        public virtual Tur Tur { get; set; }
        public virtual Yazar Yazar { get; set; }
    }
}
