//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public Ogrenci()
        {
            this.Islem = new HashSet<Islem>();
        }
    
        public int Ogrenci_ID { get; set; }
        public string AdSoy { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
        public Nullable<System.DateTime> D_Tarihi { get; set; }
        public Nullable<int> Sinif { get; set; }
        public Nullable<int> Puan { get; set; }
    
        public virtual ICollection<Islem> Islem { get; set; }
    }
}
