//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazar
    {
        public Yazar()
        {
            this.Kitap = new HashSet<Kitap>();
        }
    
        public int Yazar_ID { get; set; }
        public string Yazar_AdSoy { get; set; }
    
        public virtual ICollection<Kitap> Kitap { get; set; }
    }
}
