//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mus_Takip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public Musteriler()
        {
            this.Ucuslar = new HashSet<Ucuslar>();
        }
    
        public int Musteri_No { get; set; }
        public string Ad_Soy { get; set; }
        public string Tel_No { get; set; }
        public string TC { get; set; }
        public Nullable<System.DateTime> D_Tarihi { get; set; }
        public string E_Mail { get; set; }
        public Nullable<int> Puan { get; set; }
    
        public virtual ICollection<Ucuslar> Ucuslar { get; set; }
    }
}
