//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mus_Takip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucuslar
    {
        public int Ucus_No { get; set; }
        public string Nereden { get; set; }
        public string Nereye { get; set; }
        public Nullable<System.DateTime> Kalkis_Tar { get; set; }
        public string Kalkis_Saat { get; set; }
        public Nullable<int> Bilet_Fiyati { get; set; }
        public Nullable<int> Musteri_No { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
